In [1]:
from Resnet import ResNet, Block, create_pairs, create_tensors
import random
import pandas as pd
import numpy as np
import os
import torch
from torch.nn import TripletMarginLoss
from torchvision.io import decode_image, ImageReadMode
from torch.utils.data import Dataset, Sampler, DataLoader
from torchvision.transforms import v2
from torchvision.models import resnet50, ResNet50_Weights
from torch.optim import Adam
from collections import defaultdict
import mlflow

In [2]:
"""
creates batches with a size of 15, ensuring we are using all samples provided at random.
"""

def create_batches(label_mapping, n_classes, n_samples):
    all_classes = list(label_mapping.keys())
    batches = []
    label_mapping_copy = label_mapping.copy()
    while True:
        available_classes = [c for c in all_classes if len(label_mapping_copy[c]) > 0] # Keep only classes if they are still available.
        # Exit if we have less
        if len(available_classes) < n_classes: 
            break

        # Ensures that we will at least have 1 example of every label pair
        selected_classes = random.sample(available_classes, n_classes)
        batch = []

        for cls in selected_classes:
            indices = label_mapping_copy[cls]
            # If there are not enough examples to sample from, we re-select a sample from the shortened list. Empty the list after
            if len(indices) >= n_samples:
                chosen = indices[:n_samples]
                label_mapping_copy[cls] = indices[n_samples:]
            else:
                chosen = indices + random.choices(indices, k=(n_samples - len(indices)))
                label_mapping_copy[cls] = []

            batch.extend(chosen)

        batches.append(batch)

    return batches


class BalancedBatchSampler(Sampler):
    def __init__(self, labels, n_classes, n_samples):
        self.labels = labels
        self.n_classes = n_classes 
        self.n_samples = n_samples  

        self.label_mapping = defaultdict(list)
        for idx, label in enumerate(labels):
            self.label_mapping[int(label)].append(idx)

    def __iter__(self):
        for cls in self.label_mapping:
            random.shuffle(self.label_mapping[cls])

        batches = create_batches(self.label_mapping, self.n_classes, self.n_samples)
        for batch in batches:
            yield batch

    def __len__(self):
        batches = create_batches(self.label_mapping, self.n_classes, self.n_samples)
        return len(batches)

In [3]:
class ImageDataset(Dataset):
    def __init__(self, annotation_file, img_dir, transform=None, channel_dim=4):
        self.img_label = pd.read_csv(annotation_file)
        self.img_dir = img_dir
        self.transform = transform
        self.channel_dim = channel_dim

    def __len__(self):
        return len(self.img_label)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.img_label.iloc[idx, 0])
        if self.channel_dim == 3:
            image = decode_image(img_path, mode=ImageReadMode.RGB)
        else:
            image = decode_image(img_path)
        label = self.img_label.iloc[idx, 1]
        if self.transform:
            image = self.transform(image)

        return image, label

In [4]:
class TrainIter:
    def __init__(self, model, lr, epochs, output_size, batch_size, channel_dim, device, train_path, test_path, valid_path, img_path, output_count):
        self.device = device
        self.model = self.prepare_model(model, channel_dim, output_size).to(self.device)
        self.lr = lr
        self.epochs = epochs
        self.output_size = output_size
        self.batch_size = batch_size
        self.channel_dim = channel_dim
        self.train_path = train_path
        self.test_path = test_path
        self.valid_path = valid_path
        self.img_path = img_path
        self.output_count = output_count
        self.loss_fn = TripletMarginLoss()
        self.optimizer = Adam(self.model.parameters(), lr=self.lr)
        self.transform_data()

    def prepare_model(self, model, channel_dim, output_size):
        if model == 'resnet-scratch':
            return ResNet(Block, [3, 4, 6, 3], image_channels=channel_dim)
        else:
            model = resnet50(weights=ResNet50_Weights.DEFAULT)
            for param in model.parameters():
                param.requires_grad = False

            num_features = model.fc.in_features
            model.fc = torch.nn.Linear(num_features, output_size)
            return model


    def transform_data(self):
        transform = v2.Compose([
            v2.Resize(256),
            v2.CenterCrop(224),
            v2.ToDtype(torch.float32, scale=True)])
        self.train_data = ImageDataset(self.train_path, self.img_path, transform, self.channel_dim)
        self.valid_data = ImageDataset(self.valid_path, self.img_path, transform, self.channel_dim)
        self.test_data = ImageDataset(self.test_path, self.img_path, transform, self.channel_dim)

        df = pd.read_csv(self.train_path)
        label_tensor = torch.tensor(df['encoded_ground_truth'].values)
        sampler = BalancedBatchSampler(label_tensor, 5, 4) # n_classes, n_samples
        self.dataloader = DataLoader(self.train_data, batch_sampler=sampler, pin_memory=True)
        self.valid_dataloader = DataLoader(self.valid_data, batch_size=self.batch_size, pin_memory=True)
        self.test_dataloader = DataLoader(self.test_data, batch_size=self.batch_size, pin_memory=True)
        
    def test(self):
        self.model.eval()
        test_output = []
        test_label = []
        for batch, (X, y) in enumerate(self.test_dataloader):
            X = X.to(self.device)
            val_pred = self.model(X)
            test_output.append(test_pred.detach().cpu())
            test_label.append(y)
            
        all_preds = torch.cat(test_output, dim=0)
        all_labels = torch.cat(test_label, dim=0)
        
        pairs = create_pairs(all_labels, all_preds)
        a, p, n = create_tensors(pairs)
        test_loss = self.loss_fn(a.to(self.device), p.to(self.device), n.to(self.device))
        return test_loss.item()
        
    def validate(self):
        self.model.eval()
        val_output = []
        val_label = []
        for batch, (X, y) in enumerate(self.valid_dataloader):
            X = X.to(self.device)
            val_pred = self.model(X)
            val_output.append(val_pred.detach().cpu())
            val_label.append(y)
            
        all_preds = torch.cat(val_output, dim=0)
        all_labels = torch.cat(val_label, dim=0)
        
        pairs = create_pairs(all_labels, all_preds)
        a, p, n = create_tensors(pairs)
        val_loss = self.loss_fn(a.to(self.device), p.to(self.device), n.to(self.device))
        return val_loss.item()
    
    def train(self):
        for i in range(self.epochs):
            self.model.train()
            avg_loss = []
            for batch, (X, y) in enumerate(self.dataloader):
                self.optimizer.zero_grad()
                X, y = X.to(self.device), y.to(self.device)
                pred = self.model(X)
                pairs = create_pairs(y, pred)
                a, p, n = create_tensors(pairs)
                loss = self.loss_fn(a.to(self.device), p.to(self.device), n.to(self.device))
                loss.backward()
                self.optimizer.step()
                avg_loss.append(loss.item())
            if (i+1) % self.output_count == 0:
                with torch.no_grad():
                    val_loss = self.validate()
                print(f"Epoch {i+1}: Avg training loss - {np.mean(avg_loss)}, Avg validation loss - {val_loss}")
                mlflow.log_metric("train_loss", np.mean(avg_loss), step=i+1)
                mlflow.log_metric("valid_loss", val_loss, step=i+1)

In [5]:
mlflow.set_tracking_uri("http://127.0.0.1:5000/")
mlflow.set_experiment("Jaguar Identification")
mlflow.pytorch.autolog()
mlflow.enable_system_metrics_logging()
model_options = ['resnet-scratch', 'resnet50-pretrained']
kwargs = {
    "model": 'resnet50-pretrained',
    "lr": 0.001,
    "epochs": 50,
    "output_size": 128,
    "batch_size": 15,
    "channel_dim": 3,
    "device": torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    "train_path": 'Data/train_data.csv',
    "test_path": 'Data/test_data.csv',
    "valid_path": 'Data/valid_data.csv',
    "img_path": 'Data/train/',
    "output_count": 1
}
model = TrainIter(**kwargs)
with mlflow.start_run():
    mlflow.log_params(kwargs)
    model.train()

2026/03/06 14:56:49 INFO mlflow.system_metrics.system_metrics_monitor: Started monitoring system metrics.

Epoch 1: Avg training loss - 0.5899832790992299, Avg validation loss - 0.46659985184669495
Epoch 2: Avg training loss - 0.32025973353598075, Avg validation loss - 0.35930493474006653
Epoch 3: Avg training loss - 0.2360002697124833, Avg validation loss - 0.2708999812602997
Epoch 4: Avg training loss - 0.16144480147669393, Avg validation loss - 0.215275377035141
Epoch 5: Avg training loss - 0.11541587474235034, Avg validation loss - 0.19805532693862915
Epoch 6: Avg training loss - 0.08371993645903517, Avg validation loss - 0.19284814596176147
Epoch 7: Avg training loss - 0.05945656575107326, Avg validation loss - 0.1650274395942688
Epoch 8: Avg training loss - 0.06511684986359004, Avg validation loss - 0.15696634352207184
Epoch 9: Avg training loss - 0.054856978371166265, Avg validation loss - 0.15834307670593262
Epoch 10: Avg training loss - 0.040625312288905244, Avg validation loss - 0.14689920842647552
Epoch 11: Avg training loss - 0.03960688911439454, Avg validation loss - 0.14775991439819336
Epoch 12: Avg training loss - 0.029474452533759177, Avg validation loss - 0.1536744236946106
Epoch 13: Avg training loss - 0.02640418219714059, Avg validation loss - 0.13333472609519958
Epoch 14: Avg training loss - 0.024340357228148996, Avg validation loss - 0.13701091706752777
Epoch 15: Avg training loss - 0.021908244011067456, Avg validation loss - 0.12959565222263336
Epoch 16: Avg training loss - 0.020961195865604697, Avg validation loss - 0.13394546508789062
Epoch 17: Avg training loss - 0.02183401226551117, Avg validation loss - 0.12494243681430817
Epoch 18: Avg training loss - 0.016312169613044363, Avg validation loss - 0.1271706223487854
Epoch 19: Avg training loss - 0.018167622670835742, Avg validation loss - 0.12890173494815826
Epoch 20: Avg training loss - 0.015124273271738695, Avg validation loss - 0.11965067684650421
Epoch 21: Avg training loss - 0.017012853684199008, Avg validation loss - 0.12324485182762146
Epoch 22: Avg training loss - 0.012150301457860805, Avg validation loss - 0.12862613797187805
Epoch 23: Avg training loss - 0.013428945559199847, Avg validation loss - 0.12076447159051895
Epoch 24: Avg training loss - 0.00890493423584202, Avg validation loss - 0.11348511278629303
Epoch 25: Avg training loss - 0.011413608260139176, Avg validation loss - 0.11846395581960678
Epoch 26: Avg training loss - 0.012329130064851293, Avg validation loss - 0.11918580532073975
Epoch 27: Avg training loss - 0.009862169592745504, Avg validation loss - 0.11442677676677704
Epoch 28: Avg training loss - 0.009978461142115218, Avg validation loss - 0.11725655198097229
Epoch 29: Avg training loss - 0.0069179459860606585, Avg validation loss - 0.11577177047729492
Epoch 30: Avg training loss - 0.01206295327085627, Avg validation loss - 0.11301609128713608
Epoch 31: Avg training loss - 0.008798119383129688, Avg validation loss - 0.11562703549861908
Epoch 32: Avg training loss - 0.008618590811775143, Avg validation loss - 0.11446072161197662
Epoch 33: Avg training loss - 0.010704647481683283, Avg validation loss - 0.11106690764427185
Epoch 34: Avg training loss - 0.007920282134333413, Avg validation loss - 0.09956831485033035
Epoch 35: Avg training loss - 0.009222330962456322, Avg validation loss - 0.1189446970820427
Epoch 36: Avg training loss - 0.008558606550829356, Avg validation loss - 0.11297532916069031
Epoch 37: Avg training loss - 0.009110952758654152, Avg validation loss - 0.11523932963609695
Epoch 38: Avg training loss - 0.007572171956417151, Avg validation loss - 0.11329460889101028
Epoch 39: Avg training loss - 0.010300399695915985, Avg validation loss - 0.11542902886867523
Epoch 40: Avg training loss - 0.009632686974722067, Avg validation loss - 0.110345758497715
Epoch 41: Avg training loss - 0.007022787787837976, Avg validation loss - 0.11040365695953369
Epoch 42: Avg training loss - 0.006810188041568976, Avg validation loss - 0.11196686327457428
Epoch 43: Avg training loss - 0.005001730772496629, Avg validation loss - 0.11331319063901901
Epoch 44: Avg training loss - 0.0059978156050882235, Avg validation loss - 0.11107874661684036
Epoch 45: Avg training loss - 0.007675270528423306, Avg validation loss - 0.11622457206249237
Epoch 46: Avg training loss - 0.006497961915013753, Avg validation loss - 0.1069125235080719
Epoch 47: Avg training loss - 0.006314593259898562, Avg validation loss - 0.11099904030561447
Epoch 48: Avg training loss - 0.0057290447726638565, Avg validation loss - 0.10998639464378357
Epoch 49: Avg training loss - 0.005720054466470925, Avg validation loss - 0.11695537716150284

2026/03/06 17:22:55 INFO mlflow.system_metrics.system_metrics_monitor: Stopping system metrics monitoring...
2026/03/06 17:22:55 INFO mlflow.system_metrics.system_metrics_monitor: Successfully terminated system metrics monitoring!

Epoch 50: Avg training loss - 0.004482253306014173, Avg validation loss - 0.10878216475248337
🏃 View run rogue-trout-843 at: http://127.0.0.1:5000/#/experiments/2/runs/e22759f8eb314c88a9f4e7bb4e0cf3a5
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/2

In [113]:
from numpy import dot 
from numpy.linalg import norm 
from torch.nn.functional import cosine_similarity

In [24]:
test_dataloader = DataLoader(model.test_data, batch_size=model.batch_size, pin_memory=True)

In [35]:
X1, y1 = model.test_data[0]
X2, y2 = model.test_data[1]
X3, y3 = model.test_data[3]

In [44]:
X1 = X1.reshape(1, 3, 224, 224)
X1 = X1.to(model.device)
test_pred1 = model.model(X1)
X2 = X2.reshape(1, 3, 224, 224)
X2 = X2.to(model.device)
test_pred2 = model.model(X2)

In [46]:
test_pred1 = test_pred1.reshape(128)
test_pred2 = test_pred2.reshape(128)

In [47]:
cosine_similarity(test_pred1.detach().cpu(), test_pred2.detach().cpu())

C:\Users\Baljot\AppData\Local\Temp\ipykernel_4632\3193101217.py:6: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  return dot(v1, v2) / (norm(v1) * norm(v2))

np.float32(0.45834345)

In [27]:
test_output = []
test_label = []
for batch, (X, y) in enumerate(test_dataloader):
    X = X.to(model.device)
    test_pred = model.model(X)
    test_output.append(test_pred.detach().cpu())
    test_label.append(y)
    
all_preds = torch.cat(test_output, dim=0)
all_labels = torch.cat(test_label, dim=0)

pairs = create_pairs(all_labels, all_preds)
a, p, n = create_tensors(pairs)
test_loss = model.loss_fn(a.to(model.device), p.to(model.device), n.to(model.device))

In [26]:
test_loss

tensor(0.0984, device='cuda:0')

# Inference

In [69]:
from torchvision.io import read_image

class TestImageDataset(Dataset):
    def __init__(self, csv_file, img_dir, transform=None):
        self.data = pd.read_csv(csv_file)  # columns: image1, image2
        self.img_dir = img_dir
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img1_path = os.path.join(self.img_dir, self.data.iloc[idx, 1])
        img2_path = os.path.join(self.img_dir, self.data.iloc[idx, 2])
        img1 = decode_image(img1_path, mode=ImageReadMode.RGB)
        img2 = decode_image(img2_path, mode=ImageReadMode.RGB)

        if self.transform:
            img1 = self.transform(img1)
            img2 = self.transform(img2)
            

        return img1.reshape(1, 3, 224, 224), img2.reshape(1, 3, 224, 224)

img_path = 'Data/test/'
test_path = 'Data/test.csv'
transform = v2.Compose([
            v2.Resize(256),
            v2.CenterCrop(224),
            v2.ToDtype(torch.float32, scale=True)])
test_data = TestImageDataset(test_path, img_path, transform)

In [84]:
df_test = pd.read_csv(test_path)
res = []
rows = list(df_test.row_id)
# for r in rows:
#     X1, X2 = test_data[r]
#     X1 = X1.to(model.device)
#     X2 = X2.to(model.device)
#     res1 = model.model(X1).detach().cpu()
#     res2 = model.model(X2).detach().cpu()
#     sim = cosine_similarity(res1, res2)
#     res.append(sim)
# model.model(test_data[0][0].to(model.device)).reshape(-1)

In [91]:
df_test

        row_id    query_image  gallery_image
0            0  test_0001.png  test_0002.png
1            1  test_0001.png  test_0003.png
2            2  test_0001.png  test_0004.png
3            3  test_0001.png  test_0005.png
4            4  test_0001.png  test_0006.png
...        ...            ...            ...
137265  137265  test_0371.png  test_0366.png
137266  137266  test_0371.png  test_0367.png
137267  137267  test_0371.png  test_0368.png
137268  137268  test_0371.png  test_0369.png
137269  137269  test_0371.png  test_0370.png

[137270 rows x 3 columns]

In [94]:
df_test_1  = df_test.query_image.unique()
df_test_query = list(df_test.query_image)

In [97]:
indexs = []
for d in df_test_1:
    indexs.append(df_test_query.index(d))

In [99]:
samples = []
for idx in indexs:
    X1, X2 = test_data[idx]
    X1 = X1.to(model.device)
    res1 = model.model(X1).detach().cpu()
    samples.append(res1)

In [106]:
all_embeddings = torch.cat(samples, dim=0)

In [143]:
sim_matrix = cosine_similarity(
    all_embeddings.unsqueeze(1),  # (371, 1, dim)
    all_embeddings.unsqueeze(0),  # (1, 371, dim)
    dim=2
)
sim_matrix = (sim_matrix + 1) / 2

In [144]:
sim_matrix.shape[0]

371

In [145]:
res = []
for i in range(sim_matrix.shape[0]):
    for j in range(sim_matrix.shape[0]):
        if i == j:
            continue
        res.append(np.round(float(sim_matrix[i][j]), 4))

In [146]:
row_id = list(df_test.row_id)

In [147]:
df_final = pd.DataFrame({'row_id': row_id, 'similarity': res})
df_final = df_final.set_index('row_id')

In [148]:
df_final

        similarity
row_id
0           0.8276
1           0.6261
2           0.6278
3           0.4186
4           0.5611
...            ...
137265      0.8691
137266      0.9103
137267      0.8243
137268      0.9269
137269      0.9252

[137270 rows x 1 columns]

In [149]:
df_final.to_csv('Submission.csv')